# Define the stage for this pipeline
stages:
  - deploy

# Job to deploy the application using GitOps with ArgoCD
deploy_gitops:
  stage: deploy
  image: ubuntu:22.04  # Use Ubuntu image for flexibility with tools
  before_script:
    # Install required tools
    - apt-get update && apt-get install -y curl git
    # Install ArgoCD CLI
    - curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
    - chmod +x /usr/local/bin/argocd
    # Configure Git for committing changes
    - git config --global user.name "GitLab CI Bot"
    - git config --global user.email "ci@gitlab.com"
  script:
    # Install Azure CLI for AKS authentication
    - curl -sSL https://aka.ms/InstallAzureCLIDeb | bash
    # Log in to Azure using service principal
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    # Get AKS credentials for cluster access
    - az aks get-credentials --resource-group revisegithub --name devbook

    # Update image versions in Kubernetes manifests
    - sed -i "s|17rj/three-tier-todo-frontend:.*|17rj/three-tier-todo-frontend:${IMAGE_VERSION}|g" k8s-manifests/frontend-deployment.yaml
    - sed -i "s|17rj/three-tier-todo-backend:.*|17rj/three-tier-todo-backend:${IMAGE_VERSION}|g" k8s-manifests/backend-deployment.yaml

    # Commit updated manifests to trigger ArgoCD
    - git add k8s-manifests/
    - git commit -m "Update image versions to ${IMAGE_VERSION}" || echo "No changes to commit"
    # Push changes to the main branch
    - git push https://oauth2:${GITLAB_ACCESS_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git HEAD:main

    # Authenticate with ArgoCD and verify sync
    - argocd login $ARGOCD_SERVER --token $ARGOCD_AUTH_TOKEN
    # Sync the ArgoCD application
    - argocd app sync three-tier-app --assumeYes --timeout 300
    # Wait for the application to become healthy
    - argocd app wait three-tier-app --health --timeout 300
  environment:
    name: production  # Deploy to production environment
  tags:
    - self-hosted
