name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read


jobs:
  fullstack-build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: bookStore/pom.xml
        
    - name: Build with Maven
      working-directory: bookStore
      run: mvn clean package  -DskipTests=true
    - name: Docker Build and Push
      run: |
        docker build -t 17rj/bookstore-spring-book:latest bookStore/
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push 17rj/bookstore-spring-book:latest
